name: "Chromatic Publish"

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout studio-henk
        uses: actions/checkout@v3
        with:
          repository: studio-henk/studio-henk
          path: studio-henk
          ssh-key: ${{ secrets.STUDIO_HENK_DEPLOY_KEY }}

      - name: Recreate Shopify symlinks
        run: |
          ln -s "$GITHUB_WORKSPACE/studio-henk/snippets/henk-button.liquid" src/snippets/henk-button.liquid
          ln -s "$GITHUB_WORKSPACE/studio-henk/assets/henk-critical.css" public/assets/henk-critical.css
          ln -s "$GITHUB_WORKSPACE/studio-henk/assets/henk-css-variables.css" public/assets/henk-css-variables.css

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - run: npm ci

      - uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          exitOnceUploaded: true
